// Code generated by protoc-gen-go. DO NOT EDIT.
// source: A.proto

/*
Package test is a generated protocol buffer package.

It is generated from these files:
	A.proto

It has these top-level messages:
*/
package test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// xxxxxxxxxxxxxxxxxxxxxxxxx comments
// yyyyyyyyyyyyyyyyyyyyyyyyy comments
type SUB_CMD int32

const (
	SUB_CMD_CMD1 SUB_CMD = 257
	SUB_CMD_CMD2 SUB_CMD = 258
)

var SUB_CMD_name = map[int32]string{
	257: "CMD1",
	258: "CMD2",
}
var SUB_CMD_value = map[string]int32{
	"CMD1": 257,
	"CMD2": 258,
}

func (x SUB_CMD) Enum() *SUB_CMD {
	p := new(SUB_CMD)
	*p = x
	return p
}
func (x SUB_CMD) String() string {
	return proto.EnumName(SUB_CMD_name, int32(x))
}
func (x *SUB_CMD) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SUB_CMD_value, data, "SUB_CMD")
	if err != nil {
		return err
	}
	*x = SUB_CMD(value)
	return nil
}
func (SUB_CMD) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterEnum("test.SUB_CMD", SUB_CMD_name, SUB_CMD_value)
}

func init() { proto.RegisterFile("A.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 67 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x62, 0x77, 0xd4, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29, 0x49, 0x2d, 0x2e, 0xd1, 0x92, 0xe7, 0x62, 0x0f, 0x0e, 0x75,
	0x8a, 0x77, 0xf6, 0x75, 0x11, 0xe2, 0xe4, 0x62, 0x71, 0xf6, 0x75, 0x31, 0x14, 0x68, 0x64, 0x82,
	0x32, 0x8d, 0x04, 0x9a, 0x98, 0x00, 0x01, 0x00, 0x00, 0xff, 0xff, 0x28, 0xc5, 0x6f, 0xa9, 0x30,
	0x00, 0x00, 0x00,
}
